name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test on Rails ${{ matrix.rails_version }} and Ruby ${{ matrix.ruby_version }}
    strategy:
      matrix:
        include:
          - rails_version: ~> 7.0.0
            ruby_version: 3.2
          - rails_version: ~> 7.0.0
            ruby_version: 3.1
          - rails_version: ~> 6.1.0
            ruby_version: '3.0'
          - rails_version: ~> 6.0.0
            ruby_version: 2.7
          - rails_version: ~> 5.2.0
            ruby_version: 2.6
          - rails_version: ~> 5.1.0
            ruby_version: 2.5
    env:
      RAILS_VERSION: ${{ matrix.rails_version }}
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - name: Test
      run: bundle exec rake 
